#!/usr/bin/env python3
"""Build the standalone prompt from the authoritative skill and its references."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit

if __package__:
    from .validate import (INLINE_LINK, LINK_DEFINITION, REFERENCE_NAMES, ROOT, SKILL_PATH,
                           heading_ids, is_within, markdown_anchors, markdown_links, parse_frontmatter, read_text)
else:
    from validate import (INLINE_LINK, LINK_DEFINITION, REFERENCE_NAMES, ROOT, SKILL_PATH,
                          heading_ids, is_within, markdown_anchors, markdown_links, parse_frontmatter, read_text)


def prompt_sources(root: Path) -> list[Path]:
    skill = root / SKILL_PATH
    return [skill / "SKILL.md", *(skill / "references" / name for name in REFERENCE_NAMES), skill / "LICENSE"]


def render_prompt(root: Path) -> str:
    """Return deterministic LF text; hash includes names and all normalized source text."""
    root = root.resolve()
    skill = root / SKILL_PATH
    if not is_within(skill, root):
        raise ValueError("installed skill directory escapes the repository")
    sources = prompt_sources(root)
    texts = {}
    digest = hashlib.sha256()
    for path in sources:
        if not is_within(path, skill):
            raise ValueError(f"source escapes installed skill: {path.name}")
        text = read_text(path)
        relative = path.relative_to(root).as_posix()
        digest.update(relative.encode("utf-8") + b"\0" + text.encode("utf-8") + b"\0")
        if path.name == "SKILL.md":
            _, text = parse_frontmatter(text)
        elif path.name == "LICENSE":
            text = "# License\n\n" + text
        texts[path.resolve()] = text
    prefixes = {path.resolve(): "skill" if path.name == "SKILL.md" else path.stem.lower() for path in sources}

    def rewrite_target(source: Path, target: str) -> str:
        parts = urlsplit(target)
        if parts.scheme or parts.netloc:
            return target
        destination = (source.parent / unquote(parts.path)).resolve() if parts.path else source.resolve()
        if destination not in prefixes:
            raise ValueError(f"{source.name}: cannot bundle local link '{target}'")
        if parts.query:
            raise ValueError(f"{source.name}: local link query strings are unsupported: '{target}'")
        anchor = unquote(parts.fragment)
        if anchor and anchor not in markdown_anchors(texts[destination]):
            raise ValueError(f"{source.name}: missing source anchor in '{target}'")
        return f"#{prefixes[destination]}" + (f"--{anchor}" if anchor else "")

    def rewrite_match(source: Path, match: re.Match) -> str:
        group = "angle" if match["angle"] is not None else "bare"
        start, end = match.span(group)
        offset = match.start()
        return match[0][:start - offset] + rewrite_target(source, match[group]) + match[0][end - offset:]

    sections = []
    for source in sources:
        text = texts[source.resolve()]
        prefix = prefixes[source.resolve()]
        heading_by_line = dict(heading_ids(text))
        lines = []
        fence: tuple[str, int] | None = None
        for index, line in enumerate(text.splitlines()):
            marker = re.match(r"^\s{0,3}(`{3,}|~{3,})", line)
            if fence:
                if marker and marker[1][0] == fence[0] and len(marker[1]) >= fence[1]:
                    fence = None
            elif marker:
                fence = (marker[1][0], len(marker[1]))
            else:
                if index in heading_by_line:
                    lines.append(f'<a id="{prefix}--{heading_by_line[index]}"></a>')
                # Only transform prose segments, preserving literal examples in inline code.
                chunks = re.split(r"(`+.*?`+)", line)
                for chunk_index in range(0, len(chunks), 2):
                    chunk = INLINE_LINK.sub(lambda match: rewrite_match(source, match), chunks[chunk_index])
                    chunk = LINK_DEFINITION.sub(lambda match: rewrite_match(source, match), chunk)
                    # A source can use an explicit HTML anchor instead of an ATX heading.
                    # Prefix it as well so rewritten fragment links resolve after bundling.
                    chunk = re.sub(
                        r"(<(?:a|h[1-6])\b[^>]*\b(?:id|name)=[\"'])([^\"']+)([\"'])",
                        lambda match: f"{match[1]}{prefix}--{match[2]}{match[3]}", chunk, flags=re.I)
                    chunks[chunk_index] = chunk
                line = "".join(chunks)
            lines.append(line)
        sections.append(f'<a id="{prefix}"></a>\n\n' + "\n".join(lines).strip())
    header = (
        "<!-- Generated by python scripts/build_prompt.py. Do not edit this file directly. -->\n"
        f"<!-- Source SHA-256: {digest.hexdigest()} -->\n\n"
        "# The Specification Game — standalone prompt\n\n"
        "Copy this entire document into your assistant, then send an objective. "
        "The instructions and reference sections below form one self-contained game.\n\n"
    )
    rendered = header + "\n\n---\n\n".join(sections) + "\n"
    targets, undefined = markdown_links(rendered)
    if undefined:
        raise ValueError(f"standalone prompt has undefined link reference: {undefined[0]}")
    anchors = markdown_anchors(rendered)
    for target in targets:
        parts = urlsplit(target)
        if not parts.scheme and not parts.netloc:
            if parts.path:
                raise ValueError(f"cannot bundle local link '{target}'; put the Markdown link on one line")
            if unquote(parts.fragment) not in anchors:
                raise ValueError(f"standalone prompt has unresolved anchor: '{target}'")
    return rendered


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if PROMPT.md is missing or differs; write nothing")
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root (defaults to this checkout)")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        rendered = render_prompt(root)
        target = root / "PROMPT.md"
        if args.check:
            if not target.is_file() or read_text(target) != rendered:
                print("PROMPT.md is missing or stale. Run: python scripts/build_prompt.py", file=sys.stderr)
                return 1
            print("PROMPT.md matches the authoritative skill, all five references, and license.")
        else:
            with target.open("w", encoding="utf-8", newline="\n") as stream:
                stream.write(rendered)
            print("Wrote PROMPT.md from the authoritative skill, all five references, and license.")
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"Cannot build PROMPT.md: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
